version: 0.1
   
phases:
  install:
    commands:
      - echo 'export LC_ALL="en_US.UTF-8"' >> ~/.bashrc
      - echo 'export LANG="en_US.UTF-8"' >> ~/.bashrc
      - . ~/.bashrc
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist execjs therubyracer
  build:
    commands:
      - echo "*************** Install Required gems ***************"
      - bundle install
      - echo "*************** Building Jekyll Site ***************"
      - bundle exec jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://www.thecambridgedesign.co.uk
